global KERNEL_SIZE, BATCH_SIZE, IMG_SIZE, TIMESTEPS

KERNEL_SIZE = 3 
BATCH_SIZE = 128
# image size has to be % 2^ number_of_downscaling == 0 
IMG_SIZE = 64
TIMESTEPS = 1000
UNET_CHANNEL_BASE = 64
UNET_CHANNEL_MULT = [1,2,4,8,16]
UNET_DEPTH = 2
EPOCHS = 100

